site_name: Rico BI - Producto BI End-to-End
site_description: Documentación técnica del proyecto Rico BI para Corporación Rico S.A.C.
site_author: Equipo Rico BI

theme:
  name: readthedocs
  language: es

nav:
  - Inicio: index.md
  - Guía de ejecución: guia_ejecucion.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - admonition